### ISSUE TITLE
Improve Visibility of App Deployment Progress

### ISSUE THREAD

**Issue by seemiller** [carvel-dev/kapp-controller#110]
**Describe the problem/challenge you have**
When deploying an app using kapp-controller, it is difficult to get status or know what is happening. The current output of a `kubectl describe -n foo apps/my-app` prints out _a lot_ of information.

This information is difficult for the user to quickly get a sense of the state of the deployment. It seems like there is log type information:
```
Exit Code:  0
    Stderr:     resolve | final: gcr.io/knative-releases/knative.dev/net-contour/cmd/controller@sha256:5654ef5be4f506909bba6cbb59e7049d6c4bfc866066f2546bcabd2ff547307f -> gcr.io/knative-releases/knative.dev/net-contour/cmd/controller@sha256:5654ef5be4f506909bba6cbb59e7049d6c4bfc866066f2546bcabd2ff547307f
resolve | final: gcr.io/knative-releases/knative.dev/serving/cmd/activator@sha256:cbeb1cdcdde8b3b44bc5eb1c5a07512a36f4bd7fbee5e9677e8789ee2459b6ed -> gcr.io/knative-releases/knative.dev/serving/cmd/activator@sha256:cbeb1cdcdde8b3b44bc5eb1c5a07512a36f4bd7fbee5e9677e8789ee2459b6ed
resolve | final: gcr.io/knative-releases/knative.dev/serving/cmd/autoscaler@sha256:73d4d0503544ea930caa4fba07b701147339131de31a6aae8c52d6bb568f3c81 -> gcr.io/knative-releases/knative.dev/serving/cmd/autoscaler@sha256:73d4d0503544ea930caa4fba07b701147339131de31a6aae8c52d6bb568f3c81
resolve | final: gcr.io/knative-releases/knative.dev/serving/cmd/controller@sha256:3054c326df9de07a2a1ce34a2515339201706995a16f8efc8228295a6b94fbdd -> gcr.io/knative-releases/knative.dev/serving/cmd/controller@sha256:3054c326df9de07a2a1ce34a2515339201706995a16f8efc8228295a6b94fbdd
resolve | final: gcr.io/knative-releases/knative.dev/serving/cmd/queue@sha256:9ec8ba5c982a0a7f6dfab384365082655083413c14bdb50b01a51b730284ae32 -> gcr.io/knative-releases/knative.dev/serving/cmd/queue@sha256:9ec8ba5c982a0a7f6dfab384365082655083413c14bdb50b01a51b730284ae32
resolve | final: gcr.io/knative-releases/knative.dev/serving/cmd/webhook@sha256:07894526a4b49c61c5333e4f48190e830ce5124f0c18e1042cc15fcb594bfc37 -> gcr.io/knative-releases/knative.dev/serving/cmd/webhook@sha256:07894526a4b49c61c5333e4f48190e830ce5124f0c18e1042cc15fcb594bfc37
```

There is a massive table of `resource` information:
```
Resources in app 'knative-serving-ctrl'
Namespace        Name                                                Kind                            Owner    Conds.  Rs  Ri  Age
(cluster)        antrea-controller                                   AntreaControllerInfo            -        -       -   -   -
^                certificates.networking.internal.knative.dev        CustomResourceDefinition        kapp     2/2 t   ok  -   20h
^                config.webhook.serving.knative.dev                  ValidatingWebhookConfiguration  kapp     -       ok  -   20h
^                configurations.serving.knative.dev                  CustomResourceDefinition        kapp     2/2 t   ok  -   20h
^                images.caching.internal.knative.dev                 CustomResourceDefinition        kapp     2/2 t   ok  -   20h
^                ingresses.networking.internal.knative.dev           CustomResourceDefinition        kapp     2/2 t   ok  -   20h
...
```

While this information might be useful, it's hard to reason with and know where things go wrong.

**Describe the solution you'd like**
- The Event API should give a succinct message for each resource mutated
- Failures in the Event API should be clearly marked so that they are easy to locate
- Documentation should be updated to describe how to navigate events and logs with `kapp-controller`
- The App CR should have a status-like field that propagates the most recent error. This field should show up when `kubectl get`'ing App CRs.

**Anything else you would like to add:**
cc: @joshrosso as we wrote this feature request issue together.

**Comment by danielhelfand** [comment]
As has been discussed outside this issue, it sounds like we should put together a small proposal around some options for improving the debugging of Apps. In particular, a theme that seems to come up quite a bit with this is displaying error information in a way such that the user can quickly find what happened as opposed to having to dig through stderr output from fetch, templating, deploy, and inspect steps.

Some ideas that have been thrown around are:
* Directing stdout/stderr as k8s events 
* Having a separate status field to capture stdout/stderr

Another aspect of this we have discussed is adding documentation on debugging kapp-controller to help users solve problems quicker. This can be done in parallel to implementing any changes that come from the proposal.

This issue should be implemented before #133 and should help inform how to expose more meaningful information through InstalledPackages, which have proven difficult to debug as many users get confused by the abstraction of the underlying App produced via creating an InstalledPackage.

A minor observation I have noticed from using `kubectl` for debugging Apps is it's a bit odd that status information is displayed as `Description` when doing a `kubectl get`. The description should probably be a description for the App itself and the status information should be displayed in a separate column:

```
NAME         DESCRIPTION                                                                                            SINCE-DEPLOY   AGE
simple-app   Reconcile failed: Preparing kapp: Getting service account: serviceaccounts "default-ns-sa" not found   2s             9s
```

**Comment by aaronshurley** [comment]
Including `Explore` in the title of this issue so that we can work on a proposal for addressing this. Once a proposal is defined, we'll provide (or link to it) here.

**Comment by danielhelfand** [comment]
In researching this issue a bit further and balancing other perspectives on the topic, we aren't sure about moving forward with an Events approach to improve the debugging/progress experience of App CRs. 

One thing that we cannot accomplish through the App CR through Events is showing the deployment status of each associated resource with the App CR. This is because the stdout is coming through a kapp deploy command and cannot easily be converted to succinct Event messaging. This can also be true for error messages from Carvel tools.

Additionally, the syncing feature of Apps may lead to scenarios of logging tons of Events that also make it difficult for users to find the most meaningful Events.

Some things we think can help improve current situation:
* Having a dedicated status field that contains the most recent error message from the App CR. Instead of having a user dig through the stdout of the status, it may be better to always point users to this field to find the most relevant error message.
* Having `friendlyDescription` display more relevant information than `exit status 1`. Perhaps something that explicitly calls out to view the section of the status stderr section or proposed most recent error field.
* Documentation that clearly outlines strategies on debugging kapp-controller CRs, including those part of the packaging APIs
* In the long term, it may be helpful to completely remove stdout from the App CR status and store this information elsewhere. This will help surface errors on the status a little more clearly but preserve stdout information to be used by a UI or CLI. However, this idea hasn't been fully considered and will need more discussion to be further considered.

Because this issue doesn't necessarily have the clearest path forward, we remain open to ideas on the subject and would like to use this issue as a way to collect further feedback and ideas. It may also be worthwhile to create a GitHub discussion as a place for this conversation.

**Comment by cppforlife** [comment]
trying to address user friendly output in https://github.com/vmware-tanzu/carvel-kapp-controller/issues/412
