### ISSUE TITLE
Reference (source) PackageRepository in Package CR

### ISSUE THREAD

**Issue by joshrosso** [carvel-dev/kapp-controller#124]
**Describe the problem/challenge you have**
For client tooling, it'd be helpful if the `PackageRepository` that a `Package` CR came from was written into the `Package` object. I don't think we need a new field in the API (could be an annotation) but either could work.

**Comment by ewrenn8** [comment]
Hey @joshrosso this seems like a reasonable idea. Could you share more about the intended use for something like this, or is it just intended as an informational field?

**Comment by aaronshurley** [comment]
Some things to consider:
- can packages map to more than one package repository?
- can packages be changed (such as being updated with another package repository)?

**Comment by jorgemoralespou** [comment]
Some thoughts here, so they are not lost:

- Packages are keyed by metadata.name
- A Package with a name xyz can be contributed by multiple PackageRepositories, so names are not trully unique
- Multiple PackageRepositories can have Packages defined with the same metadata.name. There needs to exist some conflict resolution mechanism in kapp-controller.
- A Package installed on the cluster needs to have a way to prove the provenance. The PackageRepository that contributed it. IMHO this should be in the status of the Package, since it seems more related to where the Package came from rather than in the metadata or spec.
- A PackageReposiory needs to have a list of the Packages that have in the source repository and the status of whether they are contributed to the cluster or not, by any conflict

This summarizes some of the topics in a conversation on Slack.

**Comment by vrabbi** [comment]
As a user of packagea this would be a really great addition.
I have multiple package repos added to my cluster in the global namespace and would like to know which repo a package comes from.
One of the cases that came up for me was i had 3 different contour packages and it wasnt clear where each came from. Having this informatiom would be very helpfull.
Another use case ive had is that as i have multiple repos added to my cluster i would like to filter by package repo. For example if i have a stable repo and a dev repo or a vendor provided repo and a home built repo i would like an easy way to filter based on the repo so i can see what repo x or repo y is offering me to install

**Comment by joe-kimmel-vmw** [comment]
note from IPM:

- dk: "feels like an annotation" (human, not machine-automation)
- but also we should check that what we do will meet TMC's book keeping needs.  

- How does a packageCR reference a pkgr -- the 'global namespace' shows up in all other namespaces, so the pkgr reference would need to consider namespace access issues - you may be able to see a ref to a pkgr that you can't actually view.

**Comment by aaronshurley** [comment]
This was shipped in v0.33.1.
