### ISSUE TITLE
Fetch from private git repo requires write token permission

### ISSUE THREAD

**Issue by jorgemoralespou** [carvel-dev/kapp-controller#1262]
**What steps did you take:**
I have an app that fetches from a private GH repo. For this I have created a token with `read-only` permissions to content in GH Application Token generation.

**What happened:**
The app fails to fetch with:
```
Git [fetch origin]: exit status 128 (stderr: remote: Write access to repository not granted
```

**What did you expect:**
Successful fetch

**Anything else you would like to add:**
Haven't tested this in vendir, as I'm using kapp-controller and that's where I need this to work. Latest vendir is some versions ahead.

**Environment:**

- kapp Controller version (execute `kubectl get deployment -n kapp-controller kapp-controller -o yaml` and the annotation is `kbld.k14s.io/images`): 0.45.0 from cluster essentials from TMC
- Kubernetes version (use `kubectl version`): 1.25.9

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by 100mik** [comment]
I am going to try and reproduce this with vendir, we might want to move it to carvel-dev/vendir if this is a vendir issue.
Thanks for the callout @jorgemoralespou !

**Comment by rcmadhankumar** [comment]
1. Created a Private GH repository contains a simple app 
2. Created a personal access token(new fine grained personal access token) for the selected simple-app-repo, has the permission `Content: Read-Only` and `Metadata: Read-Only` (it is mandatory to give readonly permission for metadata)
3. Created a Package CR that fetches this GitHub app(fetch url is in the format `https://username:token@github.com/username/simple-app-repo.git`
4. Created a package install for the same
5. Deployed the package installs in the below versions of kapp controller

    - v0.45.0
    - v0.45.4
    - latest
 
The issue is not seen in the above mentioned versions.
Also tried to reproduce with the latest vendor version, issue is not seen there as well.

**Comment by jorgemoralespou** [comment]
Reproduced myself as well and worked with current versions, so closing it.
