### ISSUE TITLE
should we calculate next desired reconcile time from the last deploy time

### ISSUE THREAD

**Issue by cppforlife** [carvel-dev/kapp-controller#168]
**Describe the problem/challenge you have**

currently it's calculated from the last fetch time. in my case my fetch+template+deploy was taking ~30s, which means as soon as this deploy finished, next cycle was already ready to go.

should we switch to check against lastUpdatedAt for deploy? what would SINCE-DEPLOY field show in kubectl get?

**Comment by ewrenn8** [comment]
This was changed when adding the backoff logic because using last deploy would make backoff less useful in certain cases. One big reason I've heard for adding backoff is to not overwhelm fetch sources when an app is failing. The logic is set up in such a way that if we use last deploy, a newly created app that fails in the fetch or template steps will be enqueued immediately, since backoff is calculated using last deploy and last deploy is nil, which means there'll be no backoff and the app will continuously try and fetch from the source.

I could see potentially having a priority of field to use, i.e. if deploy is not nil, use deploy timestamp, otherwise use the fetch timestamp, instead of just one or the other.

**Comment by cppforlife** [comment]
> I could see potentially having a priority of field to use, i.e. if deploy is not nil, use deploy timestamp, otherwise use the fetch timestamp, instead of just one or the other.

i think it's fair that if deploy isnt set, we need to use something else.
