### ISSUE TITLE
When removing an InstalledPackage, kapp-controller should wait for the underlying App CR to be removed

### ISSUE THREAD

**Issue by cppforlife** [carvel-dev/kapp-controller#177]
**Describe the problem/challenge you have**

currently if i run `kubectl delete installedpackage foo` it will succeed and resource will be gone even though underlying App CR is still there (and terminating). should we have a finalizer that blocks installedpackage "removal" until App CR is removed?

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by danielhelfand** [comment]
I think it makes sense that the InstalledPackage deletion should wait for a successful App deletion. If there is an error with the App deletion, it would be difficult for a user to troubleshoot since we don't want users to have to be aware that an App is created for an InstalledPackage. 

My question would be how can we consistently reproduce this problem?

**Comment by cppforlife** [comment]
> My question would be how can we consistently reproduce this problem?

have an app cr that doesnt delete immediately. you can add a finalizer to any resource which would make that resource be blocked until that finalizer is gone.

**Comment by cppforlife** [comment]
available in 0.20.0-rc.1
