### ISSUE TITLE
PackageRepository Apps should be created in the namespace where kapp-controller is deployed

### ISSUE THREAD

**Issue by shivaani0505** [carvel-dev/kapp-controller#195]
**Describe the problem/challenge you have**
As of now, we do not have support for deploying kapp-controller in different namespace.
Latest alpha release uses kapp-controller namespace. As of now, I have to manually delete installed kapp-controller and re-install new kapp-controller so that all the apps can be successfully deployed and reconciled.
e.g: PackageRepositories might currently depend on kapp-controller namespace due to this is where it creates the underlying App

**Describe the solution you'd like**
[A clear and concise description of what you want to happen. If applicable a visual representation of the UX.]
We are working on package implementation in tanzu cli and fixing this would help us resolve namespace issues arising from kapp-controller.

**Anything else you would like to add:**
[Additional information that will assist in solving the issue.]

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by danielhelfand** [comment]
@shivaani0505 Thanks for opening this issue. We actually have a couple open issues that capture the essence of the problem here (#163 and #108). We are thinking the long term solution to this will be that PackageRepositories do not rely on App CRs for fetching packages as currently implemented. We could implement a temporary workaround for this, but the referenced issues are top of our backlog and it might make sense to wait for those to be implemented.

**Comment by cppforlife** [comment]
PackageRepository no longer creates underlying App CRs as of v0.20.0-rc.1
