### ISSUE TITLE
Need to view package info/metadata

### ISSUE THREAD

**Issue by qnetter** [carvel-dev/kapp-controller#267]
**Describe the problem/challenge you have**
I need to be able to decide whether a package does what I need and how to use it.

**Describe the solution you'd like**
( 2. ) As a user, I want to know some information about the package so that I can make a decision on if I should use it and how to use it. Some of this information is what will be installed in the cluster (resources), RBAC provided, description, authors, examples usage, next steps, pre-requisites.

**Anything else you would like to add:**
Our understanding of Status: Currently packages don't expose any metadata. There's a WIP to define Package metadata. No implementation has started. In latest alpha (at time of writing 0.19.0-alpha-9) some metadata is defined in a CR named InternalPackage (formerly Package).

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by jorgemoralespou** [comment]
TCE issue: https://github.com/vmware-tanzu/tce/issues/963

**Comment by ewrenn8** [comment]
Most of this information can be exposed on either the PackageMetadata CR or the Package CR. More details can be found here: https://carvel.dev/kapp-controller/docs/latest/packaging/.

In my opinion, example usages is something more fit for docs, especially because we are dealing with Kubernetes, so usages are likely blocks of yaml that need to be created in the cluster and could easily begin to clutter the other information users are trying to view. Next steps also stands out as something not currently provided in the API, but also feels more fit for documentation. 

Pre-reqs and rbac could be placed in the system requirements field of a package until we align on a better story for dependency and rbac management.

**Comment by danielhelfand** [comment]
One thing I do encounter a lot when working with users of kapp-controller's Package CR is they want to actually see what is in the fetch source (e.g. what does the imgpkg bundle actually contain). This isn't something that I think should be addressed through kapp-controller itself. It should probably be the responsibility of a CLI/UI to help users avoid needing to themselves fetch the Package's fetch source.

**Comment by aaronshurley** [comment]
@qnetter now that the CRs have been established, do you still have this need?
