### ISSUE TITLE
Reconciliation failure message being added to the FriendlyDescription instead of usefulErrorMessage

### ISSUE THREAD

**Issue by maralavi** [carvel-dev/kapp-controller#350]
**What steps did you take:**
Was working on a feature relying on Carvel Kapp Controller, and realized that after the PackageInstall reconciliation failed, the error message was not populated into the UsefulErrorMessage. 

**What happened:**
Looked at the pkgi resource and realized that the error message was being added to the FriendlyDescription instead. Looked into the carvel-kapp-controller code and realized that in SetReconcileCompleted(), UsefulErrorMessage was not set in case of an error.
https://github.com/vmware-tanzu/carvel-kapp-controller/blob/develop/pkg/reconciler/status.go#L105

**What did you expect:**
Was expecting the error message to be added into UsefulErrorMessage

**Environment:**
Vsphere

- kapp Controller version (execute `kubectl get deployment -n kapp-controller kapp-controller -o yaml` and the annotation is `kbld.k14s.io/images`): v0.23.0
-  projects-stg.registry.vmware.com/tkg/kapp-controller@sha256:1daa40ec13d04a759df7d6d3c37ce526b7287b0eb2f5529d5e4e772267d90d89

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by danielhelfand** [comment]
Hi @maralavi,

Thanks for opening this and sorry for the issues. 

The error is set [here](https://github.com/vmware-tanzu/carvel-kapp-controller/blob/e5667d3102f34e05df58e42670689b3d6ab5ee29/pkg/packageinstall/packageinstall.go#L115) in the source. This comes from the PackageInstall's App which sets its usefulErrorMessage [here](https://github.com/vmware-tanzu/carvel-kapp-controller/blob/e5667d3102f34e05df58e42670689b3d6ab5ee29/pkg/app/app_reconcile.go#L229) and [here](https://github.com/vmware-tanzu/carvel-kapp-controller/blob/e5667d3102f34e05df58e42670689b3d6ab5ee29/pkg/app/app_reconcile.go#L264).

This may be intentional as described in the documentation [here](https://carvel.dev/kapp-controller/docs/latest/debugging/#debugging-app-crs). It's not always set since some times all information can be shown in the Description column from a kubectl get. But I do see the point that it should be consistently displayed there. 

If you could share an example PackageInstall to help us reproduce, we might be able to better understand how to approach this.

**Comment by maralavi** [comment]
Hi @danielhelfand Sorry for the delay. I just updated the related PR. When I run the following after building the package plugin with the changes in [this PR](https://github.com/vmware-tanzu/tanzu-framework/pull/768), and intentionally providing an invalid version for the package, I get the following:
```
tanzu package installed update test-pkg --package-name pkg.test.carvel.dev --version 4.0.0 -n test-ns
| Updating package 'test-pkg'
- Getting package install for 'test-pkg'
- Updating package install for 'test-pkg'
| Waiting for package install reconciliation for 'test-pkg'


Error: resource reconciliation failed: . Reconcile failed: Expected to find at least one version, but did not (details: a...
Error: exit status 1

```

As you can see```status.UsefulErrorMessage``` happens to be empty in this error. Please note that if I provide invalid package name but a valid version, I get the same output.

Please note the case for "reconciliation failure" is as follows:
```
case kappctrl.ReconcileFailed:
  return false, fmt.Errorf("resource reconciliation failed: %s. %s", status.UsefulErrorMessage, status.FriendlyDescription)
```

Would it be possible that ```UsefulErrorMessage``` error message be filled for cases in which package name or version is invalid and the FriendlyDescription message change to something more user-friendly?
