### ISSUE TITLE
PackageRepository trying to delete when PackageInstall has same name and namespace

### ISSUE THREAD

**Issue by jorgemoralespou** [carvel-dev/kapp-controller#376]
**What steps did you tak and What happened:**
We deployed a PackageRepository (foo) into the default namespace (with tanzu cli repository add command) that provided a Package and PackageMetadata named foo as well.
We then run `tanzu package install foo --packagename foo.example.com --version 1.0.0 -f my-values.yaml` and then, all of a sudden, the Package and PackageMetadata foo got uninstalled, and the PackageRepository foo printed an error like this:
```
kapp: Error: Applying delete namespace/foocustom (v1) cluster:
  Deleting resource namespace/foocustom (v1) cluster: namespaces "foocustom" is forbidden:
    User "system:serviceaccount:tkg-system:kapp-controller-sa" cannot delete resource "namespaces" in API group "" in the namespace "foocustom" (reason: Forbidden)
``` 

foocustom is a value we provided in the values-file to the namespace where foo bits should be installed.

If we install the PackageRepository on the global namespace and we do the same command to install the package on default namespace, everything works fine.

[A small description of the issue]

**What did you expect:**
That the Package was properly installed

**Environment:**
- kapp Controller version (execute `kubectl get deployment -n kapp-controller kapp-controller -o yaml` and the annotation is `kbld.k14s.io/images`): v0.25.0 (upstream kapp install) and v0.23.0 (tkg 1.4 kapp-controller install)
- Kubernetes version (use `kubectl version`): 1.22.1

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by jorgemoralespou** [comment]
cc/ @andmagom

**Comment by danielhelfand** [comment]
This seems to be a conflict that occurs with kapp. Since the PackageRepository/PackageInstall have the same name in the same namespace, kapp seems to be trying to delete the PackageRepository causing its Packages to be deleted. 

To restore the PackageRepository in this case, one would need to delete the PackageInstall and then the PackageRepository should again successfully reconcile. 

The workaround here is just to make sure the PackageInstall does not have the same name as the PackageRepository. 

It's also my assumption this case could occur if someone creates a Package on its own with the same name as a PackageInstall.

**Comment by jorgemoralespou** [comment]
Hey @danielhelfand I take your comment as a workaround. I assume the underlying problem will be fixed to allow package, packagerepositories and packageinstalls to ask have the same name, which is something that makes sense from a user POV.

**Comment by danielhelfand** [comment]
I do think we should address this. Did not mean that workaround of using different name will be the solution.

I think the problem really stems from how kapp deploy -a works. Right now, kapp-controller passes the name of the repo or packageinstall to kapp which then uses the name for -a. This issue may even happen with PackageRepos and Apps.

**Comment by joe-kimmel-vmw** [comment]
In discussion the team came up with a few ideas each of which have drawbacks, interested in feedback from @jorgemoralespou and @cppforlife  :
1.) as above, kapp-controller does some "name mangling" by e.g. always appending/prepending the resource type (so e.g. a repo called "tbs" would be named "pkgr-tbs" while an install called "tbs" would be named "pkgi-tbs"). This guarantees uniqueness but at the cost of changing the name that kapp/kubectl would know about, which has the potential to confuse users. 

2.) kapp-controller could query kapp and refuse to create any new resource that would result in kapp-app name collision, and report this error to the user.  This guarantees uniqueness without mangling names, but might be frustrating UX.

3.) kapp itself could become more savvy about the types, so that from kapp's perspective a pkgi is somehow different from a pkgr is somehow different from an app.   This seems like a substantial feature in kapp.

**Comment by jorgemoralespou** [comment]
@joe-kimmel-vmw I don't know enough about the internals to give an answer, but I thought the whole point of kapp was to track generated resources via `kapp.k14s.io` labels and annotations to be able to know what to update/delete.

To me only 3 makes sense, although I thought that kapp was already savvy of types. When I look into this annotation on generated resources `kapp.k14s.io/identity: v1;default/packaging.carvel.dev/PackageInstall/my-opinionated-config;packaging.carvel.dev/v1alpha1` I would understand that there's enough information to understand the type and name of the resource.

I would need, anyways, more information to better understand your previous comment.

**Comment by danielhelfand** [comment]
Some of the challenges outlined here are the following:

The comment [here](https://github.com/vmware-tanzu/carvel-kapp-controller/issues/376#issuecomment-932530824) covers the gist of why this is happening. A simple solution to this would be adding a prefix or suffix with the resource type to handle this particular case (e.g. foo-pkgr). The issue with this approach comes with the migration of old versions of kapp-controller to new versions.

This can be shown in the following example:

Today:
1. Create a PackageRepository named foo. Result is creation of a kapp app (not an App CR) named foo-ctrl.
2. Create a PackageInstall named foo. Result is update of a kapp app named foo-ctrl to delete the PackageRepository and create a PackageInstall.

After updating to new naming scheme through kapp-controller
1. Create a PackageRepository named foo. kapp app is created called foo-pkgr-ctrl. The issue occurs here because there is no way to tell if `foo-pkgr-ctrl` is already associated with a different resource (e.g. a PackageInstall). 

Currently, kapp does not store any data in its kapp app ConfigMap to determine if updates are happening correctly for this case.

A potential long term solution could be to add a feature in kapp to support this idea, but we still need to discuss a bit further on an appropriate migration strategy to fix this bug.

**Comment by jorgemoralespou** [comment]
Is there any update on this issue?

**Comment by joe-kimmel-vmw** [comment]
@jorgemoralespou  - we looked into it long enough to agree that there was no "quick fix". @neil-hickey volunteered to do another round of digging into some of the deeper/longer options. Very much still in the exploratory (re-)design phase.

**Comment by jorgemoralespou** [comment]
Interesting. @grahamdumpleton also hit this problem today as it seems pretty common, given the recommendations and documentation that anyone will name packagerepositories, package and packageinstalls the same way.
