### ISSUE TITLE
extractImageRefHostname output doesn't container port number

### ISSUE THREAD

**Issue by blc1996** [carvel-dev/kapp-controller#549]
**What steps did you take:**
Set `dangerousSkipTLSVerify=air-gap-scale.eng.vmware.com:8043` in kapp-controller's config map 

The requests to `air-gap-scale.eng.vmware.com:8043/registry` didn't skip TLS verify

**What happened:**
The [extractImageRefHostname function](https://github.com/vmware-tanzu/carvel-kapp-controller/blob/develop/pkg/fetch/vendir.go#L359-L368) used to extract dangerousSkipTLSVerify hostname has a bug that it doesn't contain port name in the output. Even it used `hostnameAndPort` as var name.

As a result, requests to pull from `air-gap-scale.eng.vmware.com:8043/registry/xxxxx` will not skip tls even `dangerousSkipTLSVerify=air-gap-scale.eng.vmware.com:8043` is set, as `air-gap-scale.eng.vmware.com` doesn't match with `air-gap-scale.eng.vmware.com:8043`.

**What did you expect:**
The skiptls should happen as expected.

**Anything else you would like to add:**
test snippet for kapp controller host name resolve
```
package main

import (
	"fmt"
	"strings"

	"github.com/google/go-containerregistry/pkg/name"
)

func main() {
	ref := "air-gap-scale.eng.vmware.com:8043/registry/packages/core/repo:v1.22.5_vmware.1-tkg.1"
	parsedRef, err := name.ParseReference(ref)
	if err != nil {
		return
	}
	hostnameAndPort := parsedRef.Context().RegistryStr()
	fmt.Println(strings.Split(hostnameAndPort, ":")[0])
}
```
result:
```
$ go run main.go
air-gap-scale.eng.vmware.com
```

**Environment:**
kapp-controller 0.30.0

- kapp Controller version (execute `kubectl get deployment -n kapp-controller kapp-controller -o yaml` and the annotation is `kbld.k14s.io/images`):
- Kubernetes version (use `kubectl version`)

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by joe-kimmel-vmw** [comment]
The way I'm reading the code I would argue the variables are at least named correctly: 
```	
hostnameAndPort := parsedRef.Context().RegistryStr()

	return strings.Split(hostnameAndPort, ":")[0]
```

the function is called `extract...Hostname`,  so it takes something called `hostnameAndPort`, splits it on the separator char (`:`) so that the two pieces of that split would be 
[0] = hostname
[1] = port

but the function is called "extract hostname",  not "extract hostname and port" so to me based on its name that function is behaving as designed.  

Next question is whether it's a design flaw that we're only passing the hostname... I'm not sure, but my first instinct is to modify the code that's doing the check, [here](https://github.com/vmware-tanzu/carvel-kapp-controller/blob/68f387328261d5617df0536eec6f09a09c032c46/pkg/config/config.go#L127)
That code thinks it has a list of domains, which it's comparing to the "hostname" of the previous step,  but it seems like in this case the string it has is actually `domain:port` and that's why it's failing...    I'll try making a patch now.

**Comment by blc1996** [comment]
Thanks @joe-kimmel-vmw for looking into it. 
Agree that `extractImageRefHostname` is working as expected  after reading your post, missed the split part when I was reading.

**Comment by joe-kimmel-vmw** [comment]
@blc1996 - i think i can guess but would appreciate if you can confirm:    from your perspective,  you have to pass the domain with the port for everything to work,  but if you had added `domain:8043` to the `dangerousSkipTLSVerify` allow-list,   would you be surprised/disappointed/filing-another-bug-about-security  if we then skipped TLS verification for all ports on that domain?

**Comment by blc1996** [comment]
^^ Defer this question to @vijaykatam and @vuil

**Comment by vijaykatam** [comment]
If a port is specified, probably just skip tls skip verify for that instead of all ports. If another port is desired, user can specify one more item to the list.
