### ISSUE TITLE
Docs or error message should mention that Vendir has stricter semver standards than Kapp-controller

### ISSUE THREAD

**Issue by emilycoco** [carvel-dev/kapp-controller#690]
Kapp-controller uses Vendir under the hood to fetch package assets to be installed. [vendir's definition of a valid semver version](https://carvel.dev/vendir/docs/v0.27.0/versions/) is less permissive than kapp-controller's, so using a version that is valid for kapp-controller, but invalid for vendir, such as `0.0.1` for both the package version and the artifact tag results in a non-obvious error when Vendir "can't find" the artifact because it does not consider the tag to be a valid version:
```
  usefulErrorMessage: |
    vendir: Error: Syncing directory '0':
      Syncing directory '.' with imgpkgBundle contents:
        Determining tag selection:
          Expected to find at least one version, but did not (details: all=7 -> after-prereleases-filter=3 -> after-constraints-filter=0)
  version: 0.0.1
```
The docs for vendir identify the version specs pretty clearly, but for a reader starting with kapp-controller, it's easy to assume any artifact with a 3 digit version tag would be matched. It would be ideal if the version specs for the two tools matched, but if there are compatibility issues that prevent using the same spec, a note somewhere in the docs or more of a hint in the error message would cut down on debugging time. The vendir semver spec is linked in the [detailed app spec](https://carvel.dev/kapp-controller/docs/v0.36.1/app-spec/), but it's not clear that the version is the problem from the error message, so it's not the first place a reader would look.

**Comment by joe-kimmel-vmw** [comment]
@emilycoco thanks for filing this issue - can you tell us more about your use case and give a specific example to reproduce? (i.e. can you share the concrete tags and constraints you were using?)

**Comment by emilycoco** [comment]
Sure. I was testing creating a new package, so I used `0.0.1` as the package version, and I thought it made sense to match the package version to the artifact version/tag, so I used the same value, `0.0.1` in the package CR constraints.
```
    spec:
      fetch:
        - imgpkgBundle:
            image: <MY REGISTRY>/<MY PACKAGE>:0.0.1
            tagSelection:
              semver:
                constraints: "0.0.1"
```

This resulted in the error above during the fetch stage, and it took me quite a while to figure out the problem. Since then, I've also noticed that for prerelease versions, Vendir allows use of a `.`, but kapp-controller does not, and kapp-controller allows use of `-`, but Vendir does not, so the artifact tag cannot match the package version because one of the two will error out on parsing the version.  To recreate, attempt to create a kapp-controller package CR with an artifact image tag of `0.0.1` or `1.0.0.rc1`. The different version schemas make it hard to align the artifact and package versions, which is desirable for readability.

```
# valid for vendir, invalid for kapp-controller
 tagSelection:
    semver:
      constraints: "1.0.0.rc1"

# valid for kapp-controller, invalid for vendir
 tagSelection:
    semver:
      constraints: "1.0.0-rc1"
```

**Comment by cppforlife** [comment]
> Sure. I was testing creating a new package, so I used 0.0.1 as the package version, and I thought it made sense to match the package version to the artifact version/tag, so I used the same value, 0.0.1 in the package CR constraints.

=). we recommend this as well (though dont enforce) so that end users of Package CR know what software they are installing (im glad this comes as expected/wanted since we had a lot of debate on this topic internally.)

small enhancement for below snippet:
```yaml
        - imgpkgBundle:
            image: <MY REGISTRY>/<MY PACKAGE>:0.0.1
            tagSelection:
              semver:
                constraints: "0.0.1"
```

...no need to use `tagSelection` if you are explicitly specifying tag `0.0.1` in the image field, so it's just...

```yaml
        - imgpkgBundle:
            image: <MY REGISTRY>/<MY PACKAGE>:0.0.1
```

> Vendir allows use of a ., but kapp-controller does not, and kapp-controller allows use of -, but Vendir does not, so the artifact tag cannot match the package version because one of the two will error out on parsing the version.

kapp-controller delegates to vendir for all its fetching so behaviour should be exactly same for semver selection. though note that you wouldnt be really using semver selection if you just specify image field. to go a little into detail regarding versions:

- `1.0.0.rc1` is not a valid semver (accorrding to semver.org spec) hence it's not going to be allowed by either kapp-controller or vendir. to double check `vendir tools sort-semver --version '1.0.0.rc1'` will not return any versions.

- `1.0.0-rc1` is a valid semver. but it's a prerelease version so by default it's matched (both vendir and PackageInstall have a configuration to allow prerelease versions). `vendir tools sort-semver --version '1.0.0-rc1'` will not return anything but `vendir tools sort-semver --version '1.0.0-rc1' --prerelease` will. (as a side note i would recommend adding a period in `1.0.0-rc1` => `1.0.0-rc.1` so that versions can be sorted as expected once you hit rc `10`).

note that Package CR's `spec.version` expects version to be a valid semver. vendir does not put any constraints by which tag you can fetch (could be `:latest` for all we care about), however, if you use `tagSelection.semver` feature then selection would only pick up valid semver tags.

> To recreate, attempt to create a kapp-controller package CR with an artifact image tag of 0.0.1 or 1.0.0.rc1.

to double check that im not bullshitting i've successfully used this pkg https://gist.github.com/cppforlife/1b06c5bd131bf0dcf7b4798e15d4c9a8 with a PackageInstall. (note that `1.0.0.rc1` would not work per above reason that it's not a valid semver)

(btw if you want more in-sync discussion/troubleshooting we are also very active on slack).

**Comment by cppforlife** [comment]
(still thinking on where to highlight some of this info in docs...)

**Comment by emilycoco** [comment]
@cppforlife you're right, the "-" for a prerelease does work, I think I was getting confused over changing it in the 4 places version is listed and I may have only updated 3 of them when I was testing. I would have expected to get an invalid spec error when I tried to create a package CR with the version set to `0.0.1` before even trying to pull the image with that version if the two specs do come from the same place. Maybe validation is not run on the package cr version. It might help to describe this in the [debugging section](https://carvel.dev/kapp-controller/docs/v0.36.1/debugging-crs/), I couldn't find the error  described anywhere.

**Comment by cppforlife** [comment]
hmm, tried to modify `spec.version` to `0.0.1.rc1` (invalid version) and i do see it return this error:
```
% pbpaste | kubectl apply -f-
The  "pkg.test.carvel.dev.0.0.1.rc1" is invalid: spec.version: Invalid value: "0.0.1.rc1": must be valid semver: Invalid character(s) found in patch number "1.rc1"
```
with `0.0.1` it does work (https://gist.github.com/cppforlife/1b06c5bd131bf0dcf7b4798e15d4c9a8). validating tagSelection upfront within spec.fetch is much costlier so thats not done. may be that's what you ran into.

ill see if i can add some docs around versioning.

**Comment by neil-hickey** [comment]
Seems like maybe this has been done? @cppforlife Any further actions or happy to close?
