### ISSUE TITLE
Add deprecation flag to package

### ISSUE THREAD

**Issue by narahari92** [carvel-dev/kapp-controller#997]
Package of a particular version can't be supported indefinitely. There would be a time when it goes out of support. To better streamline the process, package authors have to first deprecate the package in PackageRepository and remove it from future version of PackageRepository.

So provide a way to indicate that the package is deprecated in Package CR.

Higher order systems can also use this to integrate with their notification system and provide better UX around package removal

**Comment by mamachanko** [comment]
@narahari92 I think https://github.com/vmware-tanzu/carvel-kapp-controller/pull/936 would address this, wouldn't it?

**Comment by 100mik** [comment]
I would think so!

**Comment by jorgemoralespou** [comment]
Related issue: https://github.com/vmware-tanzu/carvel-kapp-controller/issues/201

I would think that deprecation is just part of what need to be defined/implemented. A package that is installed today as the current version of a package repository might later be defined as "old/stale" for a newer version of the package repository. While the package should stick around for some versions of the packagerepository to prevent bad user experience from users, the package should also show information about whether it's recommended to be installed or not, and the reason, etc... The linked PR gives a way to show this information to the user, but it does not give a way to express when the package will be completely gone from the repository. Maybe this needs to be a policy (3 versions after yanked is defined) or (3 months after yanked is defined) maybe it needs an extra field for expressing removal date/version? Or maybe there needs to be additional functionality with regards to yanked packages in packagerepos so that by default the images contained in a yanked package are not relocated (unless explicitly defined), as relocation seems to be the biggest concern to having a package in the repo indefinitely.

**Comment by narahari92** [comment]
I've some questions around what `yank` means:
1. Does it still allow for package install to be created referencing this package version which is yanked?
2. What happens if there is already a package install referencing some package and this package gets yanked in new version of package repository?

**Comment by neil-hickey** [comment]
hey @narahari92 ! 

Let me try to answer your questions:
1. For now, we have not scoped out all the consequences of marking something as `yanked`. This iteration just displays a warning, but does not prevent the user from doing anything.
2. We expect that the likely outcome from marking a package as yanked is that we will prevent new installs, but provide an option to override that behaviour. If something gets yanked and is still in use, we will just supply a warning in the status. I don't foresee a situation where we forcefully delete a packageinstall that is now yanked. Just because something is marked as not recommended for use by an author in my opinion shouldn't force everyone off that version, but rather warn and set the right expectations to users such that they would want to get off the version.

Hopefully this helps! Do let me know if there's anything else I can try to clarify.
